### ISSUE TITLE
Webpack required? Other dependencies?

### ISSUE THREAD

**Issue by MickeyKay** [gcorne/wp-react-boilerplate#1]
Just tried to install and run `npm run build` and immediately ran into some issues that look like they have to do with dependencies. . . are there specific dependencies required to use this boilerplate? If so, maybe add them to the install notes. Thanks!

**Comment by gcorne** [comment]
> Just tried to install and run npm run build and immediately ran into some issues that look like they have to do with dependencies. . . are there specific dependencies required to use this boilerplate? If so, maybe add them to the install notes. Thanks!

@MickeyKay did you run `npm install` before running `npm run build`?

**Comment by MickeyKay** [comment]
Exactly. Thanks :)
ᐧ

On Sat, Dec 5, 2015 at 11:15 AM, Gregory Cornelius <notifications@github.com

**Comment by gcorne** [comment]
> Exactly. Thanks :)

I am updating the docs now.
