### ISSUE TITLE
Multiple stylesheets with SCSS

### ISSUE THREAD

**Issue by jamigibbs** [gcorne/wp-react-boilerplate#8]
I can't seem to get multiple SCSS files to compile into `/build/style.css`. When I `require` stylesheets in different components, only the stylesheet in `/components/widgets/` will compile (I'm trying to do this for a component that's not the widget). Maybe I'm just not clear on how to add other stylesheets?

**Comment by gcorne** [comment]
@jamigibbs Thanks for giving this a spin. I tweaked the webpack config to show how multiple multiple css files can be generated. Now if an `.scss` file is required in any module that is a dependency of `admin.js` it will be extracted into `admin.css`. Make sense?

**Comment by jamigibbs** [comment]
This is great! Thanks for doing that!
